#accounts type
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (1, 'Southern Copper Corp Del Com', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (2, 'Opportunities FD LTD (USD) Offshore', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (3, ' Global Cash (pesos) ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (4, ' Sweep Money Market Fund ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (5, 'Efectivo', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (6, 'Mexican Cetes', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (7, 'Freeport-Mcmoran Inc CL B', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (8, 'Southern Cooper LTD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (9, ' Cash, money funds and deposits ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (10, 'JPM USD Liq FD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (11, 'JPM Managed reserves FD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (12, ' Cuenta corriente ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (13, 'BNP Paribas Insticash Acc USD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (14, 'Southern Copper Corp.', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (15, 'McMoran Inc Dls', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (16, 'McMoran Inc Mxn', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (17, 'UNITED STATES TREAS BILLS 0.000% 02/01/18 B/E DTD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (18, 'UNITED STATES TREAS BILLS 0.000% 02/15/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (19, 'Nacional Financiera SNC CTF DEP', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (20, 'Nacional Financiera LONDON CD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (21, 'Nacional Financiera SNC', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (22, 'Nacional Financiera SNC LDN CD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (23, 'Nacional Financiera SNC LDN', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (24, 'NACIONAL FINANCIERA SNC LDN CERTIF OF DEPOSITS USD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (25, 'Southern Copper Corp DEL FIXED RT NT ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (26, 'Southern Copper Corp DEL NT', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (27, 'Southern Copper Corp DEL FXD RT NT', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (28, 'Petróleos Mexicanos', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (29, 'America Movil SAB de CV Sponsored ADR', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (30, 'FREEPORT- MCMORAN INC CL B', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (31, 'Southern Copper Corp', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (32, 'GBM Fondo Mexicano De dinero Pesos', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (33, 'Telesites SAB de CV Pesos ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (34, 'Daily income Govt Retail Class', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (35, 'CASH AND CASH EQUIVALENTS', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (36, 'Cash and Money Balance', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (37, 'UNITED STATES TREAS BILLS 0.000% 03/01/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (38, 'UNITED STATES TREAS BILLS 0.000% 03/15/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (39, 'UNITED STATES TREAS BILLS 0.000% 04/12/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (40, 'UNITED STATES TREAS BILLS 0.000% 04/19/18 B/E DTD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (41, 'UNITED STATES TREAS BILL DUE', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (42, 'Southern Copper Corp. 3.875', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (43, 'Southern Copper Corp. 5.25', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (44, 'Southern Copper Corp. 5.875', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (45, 'UNITED STATES TREAS BILLS 0.000% 05/17/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (46, 'UNITED STATES TREAS BILLS 0.000% 06/21/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (47, 'U S TREASURY NOTE', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (48, 'UNITED STATES TREAS BILLS 0.000% 07/19/18 B/E DTD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (49, 'UNITED STATES TREAS BILLS 0.000% 08/23/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (50, 'Nacional Financiera SNC LDN CTF DEP', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (51, 'UNITED STATES TREASURY BILL ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (52, 'UNITED STATES TREAS BILLS 0.000% 09/13/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (53, 'UNITED STATES TREAS BILLS 0.000% 09/20/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (54, 'Nacional Financiera SNC CD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (55, 'BNY MELLON US TREASURY SERV SH ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (56, 'UNITED STATES TREASURY BILLS', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (57, 'UNITED STATES TREAS BILLS 0.000% 11/23/18 B/E DTD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (58, 'UNITED STATES TREAS BILLS 0.000% 10/11/18 B/E DTD 10/12/17 ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (59, ' US TREAS BILL 01/24/19 ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (60, ' US TREAS BILL 04/25/19 ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (61, 'US TREASURY BILL 10-JAN-19', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (62, 'US TREASURY BILL 0 08-NOV-18', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (63, 'UNITED STATES TREASURY BILL 25APR19', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (64, 'UNITED STATES TREAS BILLS 0.000% 10/25/18 B/E DTD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (65, 'UNITED STATES TREAS BILLS 0.000% 11/15/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (66, 'UNITED STATES TREAS BILL DUE 02/28/19 PRINCIPAL', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (67, 'US TREASURY BILL 06-DEC-18', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (68, 'UNITED STATES TREAS BILLS 0.000% 12/06/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (69, 'UNITED STATES TREAS BILLS 0.000% 12/11/18 B/E DTD 10/18/18', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (70, 'UNITED STATES TREAS BILLS 0.000% 12/20/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (71, 'UNITED STATES TREAS BILLS 0.000% 12/18/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (72, 'UNITED STATES TREAS BILLS 0.000% 12/26/18 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (73, 'UNITED STATES TREAS BILL DUE 12/20/18 PRINCIPAL', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (74, 'UNITED STATES TREAS BILL DUE 12/13/18 PRINCIPAL', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (75, 'UNITED STATES TREAS BILL DUE 11/08/18 ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (76, 'UNITED STATES TREAS BILL DUE 12/06/18 PRINCIPAL ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (77, 'US TREASURY BILL 08-JAN-19', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (78, 'UNITED STATES TREAS BILLS 0.000% 01/08/19 B/E DTD', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (79, 'UNITED STATES TREAS BILLS 0.000% 01/15/19 B/E DTD 11/23/18 ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (80, 'UNITED STATES TREAS BILLS 0.000% 01/22/19 B/E DTD ', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (81, 'UNITED STATES TREAS BILL DUE 01/08/19 PRINCIPAL', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (82, 'UNITED STATES TREAS BILL DUE 04/11/19 PRINCIPAL', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (83, 'INVERSION', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (84, 'MERCADO DE DINERO', 1);
INSERT INTO `bank_account_type` (`id`, `name`, `status`) VALUES (85, 'TRANSACCION', 1);

#banks
INSERT INTO `bank` (`id`, `address`, `agent`, `agent_phone`, `name`, `status`, `telephone`) VALUES (1, 'dummy', 'dummy', '5555555555', 'ACTINVER SECURITIES INC', 1, '5555555555');
INSERT INTO `bank` (`id`, `address`, `agent`, `agent_phone`, `name`, `status`, `telephone`) VALUES (2, 'DUMMY', 'DUMMY', '5555555555', 'CITIBANK, N.A.', 1, '5555555555');
INSERT INTO `bank` (`id`, `address`, `agent`, `agent_phone`, `name`, `status`, `telephone`) VALUES (3, 'DUMMY', 'DUMMY', '5555555555', 'GBM INTERNATIONAL INC', 1, '5555555555');
INSERT INTO `bank` (`id`, `address`, `agent`, `agent_phone`, `name`, `status`, `telephone`) VALUES (4, 'DUMMY', 'DUMMY', '5555555555', 'JPMORGAN CHASE BANK, N.A.', 1, '5555555555');
INSERT INTO `bank` (`id`, `address`, `agent`, `agent_phone`, `name`, `status`, `telephone`) VALUES (5, 'DUMMY', 'DUMMY', '5555555555', 'BANCO SANTANDER INTERNATIONAL', 1, '5555555555');
INSERT INTO `bank` (`id`, `address`, `agent`, `agent_phone`, `name`, `status`, `telephone`) VALUES (6, 'DUMMY', 'DUMMY', '5555555555', 'UBS FINANCIAL SERVICES INC.', 1, '5555555555');
#company
INSERT INTO `company` (`id`, `friendly_account`, `name`, `rfc`, `status`) VALUES (1, 'EIM', 'EIM SA DE CV', 'EIM960825RQAA', 1);
#bank accounts
INSERT INTO `bank_account` (`id`, `account_number`, `address`, `client`, `currency`, `date`, `portfolio`, `n_status`, `telephone`, `fk_id_account_type`, `fk_id_bank`, `fk_id_company`) VALUES (1, 'NA6-013901', '5075 WESTHEIMER SUITE 650, HOUSTON TX 77056', 'SN', 'MXN', '2018-02-01 05:00:24', 'SN', 1, '7138859843', 83, 1, 1);
INSERT INTO `bank_account` (`id`, `account_number`, `address`, `client`, `currency`, `date`, `portfolio`, `n_status`, `telephone`, `fk_id_account_type`, `fk_id_bank`, `fk_id_company`) VALUES (2, '55E306656000', 'SN', 'SN', 'USD', '2018-02-01 05:02:37', 'SN', 1, '5555555555', 83, 2, 1);
INSERT INTO `bank_account` (`id`, `account_number`, `address`, `client`, `currency`, `date`, `portfolio`, `n_status`, `telephone`, `fk_id_account_type`, `fk_id_bank`, `fk_id_company`) VALUES (3, '35D021362768', 'SN', 'SN', 'USD', '2018-02-01 05:03:23', 'SN', 1, '5555555555', 83, 2, 1);
INSERT INTO `bank_account` (`id`, `account_number`, `address`, `client`, `currency`, `date`, `portfolio`, `n_status`, `telephone`, `fk_id_account_type`, `fk_id_bank`, `fk_id_company`) VALUES (4, '38451127', 'SN', 'SN', 'USD', '2018-02-01 05:04:08', 'SN', 1, '5555555555', 84, 2, 1);
INSERT INTO `bank_account` (`id`, `account_number`, `address`, `client`, `currency`, `date`, `portfolio`, `n_status`, `telephone`, `fk_id_account_type`, `fk_id_bank`, `fk_id_company`) VALUES (5, '10116373', 'SN', 'SN', 'USD', '2018-02-01 05:05:00', 'SN', 1, '5555555555', 85, 2, 1);
INSERT INTO `bank_account` (`id`, `account_number`, `address`, `client`, `currency`, `date`, `portfolio`, `n_status`, `telephone`, `fk_id_account_type`, `fk_id_bank`, `fk_id_company`) VALUES (6, 'NG0-002089', '2700 POST OAK BLVD SUITE 1110, HOUSTON TX 77056', 'SN', 'MXN', '2018-02-01 05:05:30', 'SN', 1, '2817459100', 83, 3, 1);
INSERT INTO `bank_account` (`id`, `account_number`, `address`, `client`, `currency`, `date`, `portfolio`, `n_status`, `telephone`, `fk_id_account_type`, `fk_id_bank`, `fk_id_company`) VALUES (7, 'W90679007', '270 PARK AVENUE, NEW YORK, NY 10017-2014', 'SN', 'USD', '2018-02-01 05:06:18', 'SN', 1, '5555555555', 83, 4, 1);
INSERT INTO `bank_account` (`id`, `account_number`, `address`, `client`, `currency`, `date`, `portfolio`, `n_status`, `telephone`, `fk_id_account_type`, `fk_id_bank`, `fk_id_company`) VALUES (8, '43451 - A43451', '1401 BRICKELL AVENUE, MIAMI, FL 33131', 'SN', 'USD', '2018-02-01 05:07:18', 'SN', 1, '5555555555', 83, 5, 1);
INSERT INTO `bank_account` (`id`, `account_number`, `address`, `client`, `currency`, `date`, `portfolio`, `n_status`, `telephone`, `fk_id_account_type`, `fk_id_bank`, `fk_id_company`) VALUES (9, 'AE P3195 DS', '1285 AVENUE OF AMERICAS, NEW YORK NY 10019', 'SN', 'USD', '2018-02-01 05:08:11', 'JUAN DIEZ', 1, '2126497575', 83, 6, 1);

